import React from "react";
import { Footer } from "./Footer";
import { Home } from "./Home";
import "./globals.css";


interface Props {
  children?: React.ReactNode;
}

export const metadata = {
  title: "Project_nextjs_ex",
  description: "Generated by create dy",
};

export default function RootLayout({ children }: Props) {
  return (
    <html>
      <body>
        <Home />
        {children}
        <Footer />
      </body>
    </html>
  );
}
