import { Inter } from "next/font/google";
import "./globals.css";
import { Home } from "./Home";
import { Footer } from "./Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Project_nextjs_ex",
  description: "Generated by create dy",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Home />
        {children}
        <Footer />
      </body>
    </html>
  );
}
